server:
  port: 8080
spring:
  application:
    name: baseinfo
eureka:
  client:
    serviceUrl:
      defaultZone: http://${MSE_EUREKA_URL}:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: ${ENDPOINT_HOST}
    nonSecurePort: ${ENDPOINT_PORT}


