server:
  port: 8080
spring:
  application:
    name: portal-www
eureka:
  client:
    serviceUrl:
      defaultZone: http://mse-db297472-p.eureka.mse.aliyuncs.com:8761/eureka
instance:
  preferIpAddress: true
